application: gan-sha
version: 1
runtime: python
api_version: 1
skip_files: |
 ^(.*/)?(
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 )$

default_expiration: '3650d'

handlers:
- url: /static
  static_dir: static
  secure: optional
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /console/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /test.*
  script: gaeunit.py

- url: /media
  static_dir: _generated_media

- url: /bg-tasks/.*
  script: common/appenginepatch/main.py
  secure: optional
  login: admin

- url: /gaebar/static
  static_dir: gaebar/static

- url: /.*
  script: common/appenginepatch/main.py
  secure: optional
